### ISSUE TITLE
[#1] Error with removing picture in Album

### ISSUE THREAD

**Issue by jeonmmingu** [App-in-App-le/NostelgiAlbum#24]
### **`# SITUATION`**
새로운 앨범을 생성하고 사진을 하나 추가한 후, 해당 사진을 지운 상황
### **`# ISSUE`**
사진을 지운 후, 추가하는 "+" 버튼을 Long press Gesture 를 수행할 경우 다시 삭제 문구가 표시 됨

**Comment by chopmozzi** [comment]
i will check it. thx

**Comment by jeonmmingu** [comment]
### **`Solved`**
- CollectionView 에서 ReloadData() method를 사용 시, 모든 Cell 정보를 삭제하는 것이 아니라 이전의 Cell 정보를 가지고 있다는 것을 알게 되었다. 
- 즉, Delete에 관련한 알고리즘을 생성하려면 Cell의 정보만 삭제하는 것이 아닌 Cell에 포함된 SubView 정보 또한 전부 초기화 한 후 업데이트를 진행해야한다.
### **`Additional Knowledge`**
- UIButton과 UILabel을 초기화하려면 내부에 속성들도 전부 초기화 시켜준 후, nil을 할당하여야 완전하게 메모리에서 해제된다.
- 만약 UIButton에 이미지가 포함되어 있는 상황에서 `UIInstance = nil` 이런 식으로 할당을 해제하면 ARC가 줄어들지 않아 메모리에 잔재하게 된다.
- 이는 UIButton 및 여러 UIkit에 내장된 Class들의 Properties가 reference 방식을 채택했기 때문이다.

**Comment by chopmozzi** [comment]
Goood 👍
