### ISSUE TITLE
[#2] Crop occurs when saving horizontally long pictures in AlbumPicView

### ISSUE THREAD

**Issue by jeonmmingu** [App-in-App-le/NostelgiAlbum#27]
### **`# SITUATION`**
앨범에 가로가 긴 사진을 추가하고 추가한 사진을 누른 상황
### **`# ISSUE`**
사진이 잘리는 현상이 발생

**Comment by chopmozzi** [comment]
해-결 추후 pr로 코드 올리고 닫겠습니다.

**Comment by jeonmmingu** [comment]
알겠습니다 👍🏻

**Comment by chopmozzi** [comment]
[해당 PR](https://github.com/App-in-App-le/NostelgiAlbum/pull/31/commits/c280222650db3a95df3f2e7e828061a8fdf37f58)
처음부터 resize적용 안 되어 있었습니다.
