### ISSUE TITLE
[#3] About UIImagePickerController alloc init

### ISSUE THREAD

**Issue by chopmozzi** [App-in-App-le/NostelgiAlbum#29]
AlbumEditViewController에서 UIImagePickerController를 불러올 때 생기는 문제
해당 issue는 Debug 모드에서만 생기는 문제로 확인([관련 링크)](https://stackoverflow.com/questions/20353492/uiimagepickercontroller-really-slow-when-calling-alloc-init
)
Device에 설치 후 디버그 모드를 실행하지 않고 빌드 시 문제가 생기지 않는걸 파악할 수 있음

**Comment by jeonmmingu** [comment]
확인했습니다 👍🏻
